services:
  payload:
    container_name: badertech
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media
      - ./src:/app/src
    ports:
      - "3333:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    environment:
      - PAYLOAD_SECRET=secret
      - DATABASE_URL=postgresql://badertech:secret@db/badertechdb
      - NEXT_PUBLIC_SERVER_URL=https://badertech.codenik.in
      - NEXT_PUBLIC_ORG_NAME=Badertech
    networks:
      - default-net
    
    
  db:
    image: docker.io/library/postgres:latest
    environment:
      - POSTGRES_USER=badertech
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=badertechdb
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10ss
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default-net
volumes:
  postgres-data:


networks:
  default-net:
   driver: bridge
